backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "grants"
    label: "Granty"
    folder: "_grants"  # Zmieniamy folder na _grants
    create: true      # Teraz możemy tworzyć nowe pliki
    slug: "{{id}}"  # slug z samego id
    format: "yml"
    fields:
        - { label: "id", name: "id", widget: "string", required: true }
        - { label: "Rok", name: "year", widget: "string", required: true }
        - { label: "Tytuł", name: "title", widget: "string", required: true }
        - { label: "Opis", name: "description", widget: "string", required: true}
