backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }

  - name: "grants"
    label: "Granty"
    folder: "_grants"
    create: true
    slug: "{{title}}" # Plik będzie nazwany na podstawie tytułu
    format: "yaml-frontmatter"     # Plik zapisany jako YAML
    extension: "md" 
    fields:
      - { label: "Rok", name: "year", widget: "string", required: true }
      - { label: "Tytuł", name: "title", widget: "string", required: true }
      - { label: "Opis", name: "description", widget: "text", required: true }

  - name: "publications"
    label: "Publikacje"
    folder: "_publications"
    create: true
    slug: "{{title}}" # Plik będzie nazwany na podstawie tytułu
    format: "yaml-frontmatter" # Użycie YAML z front matter
    extension: "md" # Pliki będą miały rozszerzenie .md
    fields:
      - { label: "Nazwa rozdziału", name: "section", widget: "string", required: true }
      - { label: "Rok", name: "year", widget: "number", required: true }
      - { label: "Przypis", name: "citation", widget: "text", required: true }
