backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "grants"
    label: "Granty"
    folder: "_data" # ścieżka do folderu, w którym znajdują się pliki z danymi (koniecznie)
    create: false  # blokujemy tworzenie nowych plików w folderze _data z poziomu CMS
    slug: "{{year}}" # ustawiamy slug (nazwę pliku) - z tego zrobiony bedzie _data/grants/<slug>.yml
    extension: "yml"  # ustalamy domyślne rozszerzenie
    format: "yml" # format danych
    fields:
      - label: "Lista grantów"
        name: "grants"
        widget: "list"
        fields:
          - { label: "Rok", name: "year", widget: "string" }
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }
