backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "grants"
    label: "Granty"
    folder: "_data"  # Wskazujemy folder, w którym znajdują się dane
    create: false # Nie chcemy, aby użytkownik tworzył nowe pliki .yml, tylko modyfikował istniejące.
    slug: "{{year}}-{{title}}" #  Jakie jest ID edytowanego pliku
    format: "yml" # Określamy, że edytowane dane są w formacie YML
    fields: # Określamy, które pola można modyfikować
        - { label: "Rok", name: "year", widget: "string" }
        - { label: "Tytuł", name: "title", widget: "string" }
        - { label: "Opis", name: "description", widget: "text" }
