backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "grants"
    label: "Granty"
    folder: "_data"
    create: false
    slug: "{{year}}-{{title}}" # <-- Dodane pole slug
    format: "yml"
    fields:
        - { label: "Rok", name: "year", widget: "string" }
        - { label: "Tytuł", name: "title", widget: "string" }
        - { label: "Opis", name: "description", widget: "text" }
