backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads" # Folder na przesyłane pliki w repozytorium
public_folder: "/assets/uploads" # Ścieżka publiczna do mediów

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "O mnie"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "grants"
    label: "Granty"
    file: "_data/grants.yml" # Poprawione
    fields:
      - { label: "Lista grantów", name: "grants", widget: "list", fields:
          [
            { label: "Rok", name: "year", widget: "number" },
            { label: "Tytuł", name: "title", widget: "string" },
            { label: "Opis", name: "description", widget: "text" }
          ]
        }
